name: maven-build

on:
  push:
    branches-ignore:
      - 'master'
      - 'release**'
jobs:
  maven-build-deploy:
    runs-on: [ self-hosted,linux,x64,insights ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Build with Offline dependencies Maven
        run: mvn  --batch-mode dependency:go-offline

      - name: Build with Maven
        env:
        run: mvn --batch-mode clean install